# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b79b0e1e9e573471faa7f0795212d1f8b5c0659bef0e1381d15a2b1d71aed677484fff9d214991709011d67b9763dfe4b7c442388a971843df737b3c5e19890f

test:
  secret_key_base: 1625989cba9a2f4538a048a6626760f4c572644149c0df6202d255d6b92f72996297d204c7e7a6b70d168d0d121d7189973509ea43d2a5191bded67bc1e053f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
